[package]
name = "ic_upload_minimal"
version = "0.1.0"
edition = "2021"

[lib]
name = "ic_upload_minimal"
path = "src/lib.rs"

[dependencies]
candid = "0.10"
serde = { version = "1.0", features = ["derive"] }
